### ISSUE TITLE
Missing file when running Build.PL script

### ISSUE THREAD

**Issue by hcaelc** [tokuhirom/Class-ErrorHandler#1]
I just downloaded Class-ErrorHandler-0.03 & the only build option was the Build.PL path (no Makefile.PL path available).  You provided no build instructions with your module.

So I ran:
 perl Build.PL --install_base /usr/xyz   (to install the module in an alternate location.)
But the above command generated an error and aborted due to a missing file in your build.  The missing file was MYMETA.json
# Here's the output to the command.  Is there any way around this error?  The module won't build until I'm passed it.  And it does the same error even if I remove the options!

Creating custom builder _build/lib/MyBuilder.pm in _build/lib
Checking whether your kit is complete...
Looks good

Checking prerequisites...
Looks good

Creating new 'Build' script for 'Class-ErrorHandler' version '0.03'
load_file() requires a valid, readable filename at Build.PL line 53

**Comment by tokuhirom** [comment]
I use EU::MM instead of M::B. Try new version!
